In [41]:
import torch
import torch.nn as nn

inputs=torch.Tensor(1,1,28,28)                      # batch_size, channel, height, width    (batch_size: 한 번에 모델에 입력되는 데이터 샘플의 수)
conv1=nn.Conv2d(1,32,3,padding=1)                   # input_channel수, output_channel수, filter_size(filter의 height*width)
pool=nn.MaxPool2d(2)                                # stride값은 입력이 None일 경우 kernel_size를 따라간다.
print(pool)                                     

    # 참고: Conv2d의 필터(커널) 값들은 학습을 통해 자동으로 조정됩니다. Conv2d의 필터 값들은 신경망 학습 초기화 단계에서 무작위로 설정됩니다. 
    # 이러한 초기 값들은 임의의 작은 값으로 설정되며, 학습을 통해 점차 최적화됩니다. 
    # 초기화 방법은 여러 가지가 있을 수 있는데, 가장 많이 사용되는 방법은 He 초기화나 Xavier 초기화입니다.

MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)


In [42]:
conv2=nn.Conv2d(32,64,3,padding=1)                      
print(conv1)
print(conv2)

out=conv1(inputs)
print(out)
print(out.shape)

Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
tensor([[[[ 0.1611,  0.1611,  0.1611,  ...,  0.1611,  0.1611,  0.1611],
          [ 0.1611,  0.1611,  0.1611,  ...,  0.1611,  0.1611,  0.1611],
          [ 0.1611,  0.1611,  0.1611,  ...,  0.1611,  0.1611,  0.1611],
          ...,
          [ 0.1611,  0.1611,  0.1611,  ...,  0.1611,  0.1611,  0.1611],
          [ 0.1611,  0.1611,  0.1611,  ...,  0.1611,  0.1611,  0.1611],
          [ 0.1611,  0.1611,  0.1611,  ...,  0.1611,  0.1611,  0.1611]],

         [[ 0.3163,  0.3163,  0.3163,  ...,  0.3163,  0.3163,  0.3163],
          [ 0.3163,  0.3163,  0.3163,  ...,  0.3163,  0.3163,  0.3163],
          [ 0.3163,  0.3163,  0.3163,  ...,  0.3163,  0.3163,  0.3163],
          ...,
          [ 0.3163,  0.3163,  0.3163,  ...,  0.3163,  0.3163,  0.3163],
          [ 0.3163,  0.3163,  0.3163,  ...,  0.3163,  0.3163,  0.3163],
          [ 0.3163,  0.3163,  0.3163,  ...,  

In [43]:
out=pool(out)
print(out)
print(out.shape)

tensor([[[[ 0.1611,  0.1611,  0.1611,  ...,  0.1611,  0.1611,  0.1611],
          [ 0.1611,  0.1611,  0.1611,  ...,  0.1611,  0.1611,  0.1611],
          [ 0.1611,  0.1611,  0.1611,  ...,  0.1611,  0.1611,  0.1611],
          ...,
          [ 0.1611,  0.1611,  0.1611,  ...,  0.1611,  0.1611,  0.1611],
          [ 0.1611,  0.1611,  0.1611,  ...,  0.1611,  0.1611,  0.1611],
          [ 0.1611,  0.1611,  0.1611,  ...,  0.1611,  0.1611,  0.1611]],

         [[ 0.3163,  0.3163,  0.3163,  ...,  0.3163,  0.3163,  0.3163],
          [ 0.3163,  0.3163,  0.3163,  ...,  0.3163,  0.3163,  0.3163],
          [ 0.3163,  0.3163,  0.3163,  ...,  0.3163,  0.3163,  0.3163],
          ...,
          [ 0.3163,  0.3163,  0.3163,  ...,  0.3163,  0.3163,  0.3163],
          [ 0.3163,  0.3163,  0.3163,  ...,  0.3163,  0.3163,  0.3163],
          [ 0.3163,  0.3163,  0.3163,  ...,  0.3163,  0.3163,  0.3163]],

         [[ 0.2755,  0.2755,  0.2755,  ...,  0.2755,  0.2755,  0.2755],
          [ 0.2755,  0.2755,  

In [44]:
out=conv2(out)
print(out)
print(out.shape)

tensor([[[[ 0.0910,  0.1073,  0.1073,  ...,  0.1073,  0.1073,  0.0559],
          [ 0.0807,  0.0987,  0.0987,  ...,  0.0987,  0.0987,  0.0243],
          [ 0.0807,  0.0987,  0.0987,  ...,  0.0696,  0.0987,  0.0243],
          ...,
          [ 0.0807,  0.0987,  0.0987,  ...,  0.0987,  0.0987,  0.0243],
          [ 0.0807,  0.0987,  0.0987,  ...,  0.0987,  0.0987,  0.0243],
          [ 0.0623,  0.0467,  0.0467,  ...,  0.0467,  0.0467,  0.0028]],

         [[-0.0717, -0.0736, -0.0736,  ..., -0.0736, -0.0736,  0.0101],
          [-0.1155, -0.1484, -0.1484,  ..., -0.1484, -0.1484, -0.0358],
          [-0.1155, -0.1484, -0.1484,  ..., -0.1282, -0.1484, -0.0358],
          ...,
          [-0.1155, -0.1484, -0.1484,  ..., -0.1484, -0.1484, -0.0358],
          [-0.1155, -0.1484, -0.1484,  ..., -0.1484, -0.1484, -0.0358],
          [-0.0085, -0.0357, -0.0357,  ..., -0.0357, -0.0357, -0.0083]],

         [[-0.0167, -0.0222, -0.0222,  ..., -0.0222, -0.0222,  0.0027],
          [-0.0334, -0.0101, -

In [45]:
out=pool(out)
print(out)
print(out.shape)

tensor([[[[ 0.1073,  0.1073,  0.1073,  ...,  0.1073,  0.1073,  0.1073],
          [ 0.0987,  0.0987,  0.1426,  ..., -0.0710,  0.0696,  0.0987],
          [ 0.0987,  0.0987,  0.1893,  ...,  0.1570, -0.0113,  0.0987],
          ...,
          [ 0.2099,  0.2897,  0.2071,  ...,  0.2023,  0.1698,  0.0724],
          [ 0.1391,  0.1011,  0.0987,  ...,  0.0987,  0.0987,  0.0987],
          [ 0.0987,  0.0987,  0.0987,  ...,  0.0987,  0.0987,  0.0987]],

         [[-0.0717, -0.0736, -0.0736,  ..., -0.0736, -0.0736,  0.0101],
          [-0.1155, -0.1484, -0.1484,  ..., -0.0885,  0.0210, -0.0358],
          [-0.1155, -0.1484, -0.1484,  ..., -0.1921, -0.0481, -0.0358],
          ...,
          [-0.1155, -0.3443, -0.2349,  ..., -0.2211, -0.1538, -0.0194],
          [-0.1155, -0.1484, -0.1484,  ..., -0.1476, -0.1421, -0.0358],
          [-0.0085, -0.0357, -0.0357,  ..., -0.0357, -0.0357, -0.0083]],

         [[-0.0101, -0.0101, -0.0101,  ..., -0.0101, -0.0101,  0.0094],
          [-0.0101, -0.0101,  

In [46]:
print(out.size(0))
print(out.size(1))
print(out.size(2))
print(out.size(3))

1
64
7
7


In [47]:
out=out.view(out.size(0),-1)
print(out.shape)

torch.Size([1, 3136])


In [48]:
fc=nn.Linear(3136,10)
out=fc(out)
print(out)
print(out.shape)

tensor([[ 0.1138, -0.0751,  0.2452, -0.1299, -0.0403, -0.0850, -0.0217,  0.0626,
         -0.1243, -0.1138]], grad_fn=<AddmmBackward0>)
torch.Size([1, 10])


본격적으로 코드 작성

In [ ]:
import torch
import torch.nn as nn
import torchvision.datasets as dsets
import torchvision.transforms as transforms 

import torch.nn.init                                # 텐서 초기화(initialization) 함수들을 제공하는 모듈

In [ ]:
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')

torch.manual_seed(777)
if device=='cuda':
    torch.cuda.manual_seed_all(777)

# parameters
learning_rate=0.001
training_epochs=15
batch_size=100

# MNIST dataset
mnist_train=dsets.MNIST(root='C:/git_experiment/RWL_Intern/dh_workspace/모두를 위한 딥러닝/MNIST',
                        train=True,
                        transform=transforms.ToTensor(),
                        download=True)      #transform은 input data를 어떻게 변환해줄 거냐를 의미함. 
                                            #그냥 받아오면 Tensor value가 아니므로받아온 mnist data를 tensor value로 바꿔준다.
                                            #이미지를 ToTensor로 하면 예를들어 픽셀 값이 0-255의 값일 때 정규화를 적용해서 0-1의 값으로 바꾼다.
mnist_test=dsets.MNIST(root='C:/git_experiment/RWL_Intern/dh_workspace/모두를 위한 딥러닝/MNIST',
                       train=False,
                       transform=transforms.ToTensor(),
                       download=True)

In [51]:
data_loader=torch.utils.data.DataLoader(dataset=mnist_train,
                                        batch_size=batch_size,
                                        shuffle=True,
                                        drop_last=True)

In [ ]:
class CNN(nn.Module):
    def __init__(self):
        super(CNN,self).__init__()                  #  CNN,self는 현재 클래스(여기서는 CNN)와 현재 객체(여기서는 self)를 명시적으로 지정하는 
        self.layer1=torch.nn.Sequential(
            torch.nn.Conv2d(1,32,kernel_size=3,stride=1, padding=1),
            torch.nn.ReLU(),
            nn.MaxPool2d(2)                         # MaxPool2d를 거쳐도 채널의 개수는 변하지 않는다.
        )

        self.layer2=torch.nn.Sequential(
            nn.Conv2d(32,64, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.fc=nn.Linear(7*7*64, 10, bias=True)
        torch.nn.init.xavier_uniform_(self.fc.weight)

    def forward(self,x):
        out=self.layer1(x)
        out=self.layer2(out)

        out=out.view(out.size(0),-1)        # out.size(0)은 batch_size -->out.view(out.size(0),-1): (batch_size ,14*7*7)
        out=self.fc(out)
        return out

In [ ]:
model=CNN().to(device)              # model을 device로

In [ ]:
criterion=nn.CrossEntropyLoss().to(device)              # loss_function을 device로
optimizer=torch.optim.Adam(model.parameters(), lr=learning_rate)

In [ ]:
#training 하는 코드
total_batch=len(data_loader)                # 전체 배치 수가 나온다.
for epoch in range(training_epochs):
    avg_cost=0

    for X,Y in data_loader:
        X=X.to(device)                      # cuda 연산을 진행하려면 해야한다. 이미지를 device로
        Y=Y.to(device)                      # cuda 연산을 진행하려면 해야한다.  label을 device로

        optimizer.zero_grad()
        hypothesis=model(X)
        cost=criterion(hypothesis,Y)
        cost.backward()
        optimizer.step()

        avg_cost+=cost/total_batch

    print('epoch: {} cost: {}'.format(epoch+1,avg_cost))

print('learning finished')

epoch: 1 cost: 0.22577328979969025
epoch: 2 cost: 0.06306502223014832
epoch: 3 cost: 0.04632473364472389
epoch: 4 cost: 0.03743469715118408
epoch: 5 cost: 0.03137858211994171
epoch: 6 cost: 0.026164093986153603
epoch: 7 cost: 0.021853219717741013
epoch: 8 cost: 0.018350539728999138
epoch: 9 cost: 0.016098221763968468
epoch: 10 cost: 0.013577586971223354
epoch: 11 cost: 0.010142168030142784
epoch: 12 cost: 0.01027227658778429
epoch: 13 cost: 0.008242693729698658
epoch: 14 cost: 0.006388708483427763
epoch: 15 cost: 0.006578456610441208
learning finished


In [ ]:
#test
with torch.no_grad():
    X_test=mnist_test.test_data.view(len(mnist_test),1,28,28).float().to(device)        #test 이미지 추출. 원래는 (10000,28,28)인데 view를 통해 (10000,1,28,28)
    Y_test=mnist_test.test_labels.to(device)                                            #test 라벨 추출.   shape은 (10000,)

    prediction=model(X_test)
    correct_prediction=torch.argmax(prediction,1)==Y_test                               #torch.argmax는 인수로 (예측값을 가진 텐서, dim)을 받는다.
    accuracy=correct_prediction.float().mean()                                          # 이 값은 단일 Tensor값이다.
    print('Accuracy:',accuracy.item())                                                  # 따라서 우리가 원하는 Python float값으로 출력하려면 .item()을 해줘야함.

Accuracy: 0.9857999682426453


c:\Users\dhlee\anaconda3\Lib\site-packages\torchvision\datasets\mnist.py:81: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
c:\Users\dhlee\anaconda3\Lib\site-packages\torchvision\datasets\mnist.py:71: UserWarning: test_labels has been renamed targets
  warnings.warn("test_labels has been renamed targets")


layer를 늘려보자.

In [ ]:
import torch
import torch.nn as nn
import torchvision.datasets as dsets
import torchvision.transforms as transforms 

import torch.nn.init

device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')

torch.manual_seed(777)
if device=='cuda':                          # 만약 device가 cuda일 때
    torch.cuda.manual_seed_all(777)         # 모든 cuda에 대해 난수를 생성해라(manual_seed_all)

# parameters
learning_rate=0.001
training_epochs=15
batch_size=100

# MNIST dataset
mnist_train=dsets.MNIST(root='C:/git_experiment/RWL_Intern/dh_workspace/모두를 위한 딥러닝/MNIST',
                        train=True,
                        transform=transforms.ToTensor(),        #흑백 이미지일 때는 channel수가 1, 컬러 이미지면 channel 수가 3
                        download=True)      #transform은 input data를 어떻게 변환해줄 거냐를 의미함. 
                                            #그냥 받아오면 Tensor value가 아니므로받아온 mnist data를 tensor value로 바꿔준다.
mnist_test=dsets.MNIST(root='C:/git_experiment/RWL_Intern/dh_workspace/모두를 위한 딥러닝/MNIST',
                       train=False,
                       transform=transforms.ToTensor(),
                       download=True)

data_loader=torch.utils.data.DataLoader(dataset=mnist_train,
                                        batch_size=batch_size,
                                        shuffle=True,
                                        drop_last=True)

class CNN(nn.Module):
    def __init__(self):
        super(CNN,self).__init__()
        self.layer1=torch.nn.Sequential(
            torch.nn.Conv2d(1,32,kernel_size=3,stride=1, padding=1),
            torch.nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.layer2=torch.nn.Sequential(
            nn.Conv2d(32,64, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.layer3=nn.Sequential(
            nn.Conv2d(64,128,kernel_size=3,stride=1,padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )
        self.fc1=nn.Linear(3*3*128, 625)
        self.relu=nn.ReLU()
        self.fc2=nn.Linear(625, 10, bias=True)
        torch.nn.init.xavier_uniform_(self.fc1.weight)
        torch.nn.init.xavier_uniform_(self.fc2.weight)

    def forward(self,x):
        out=self.layer1(x)
        out=self.layer2(out)
        out=self.layer3(out)

        out=out.view(out.size(0),-1)            # 이걸 하는 이유: convolution layer를 지난 결과들을 fully connected layer에 넣어야 하기 때문에 입력 개수만큼 바꿔주기 위해서.
        out=self.fc1(out)
        out=self.relu(out)
        out=self.fc2(out)
        return out
    
model=CNN().to(device)

criterion=nn.CrossEntropyLoss().to(device)
optimizer=torch.optim.Adam(model.parameters(), lr=learning_rate)

#training 하는 코드
total_batch=len(data_loader)                # 전체 배치 수가 나온다.
for epoch in range(training_epochs):
    avg_cost=0

    for X,Y in data_loader:
        X=X.to(device)                      # cuda 연산을 진행하려면 해야한다.
        Y=Y.to(device)                      # cuda 연산을 진행하려면 해야한다.

        optimizer.zero_grad()
        hypothesis=model(X)
        cost=criterion(hypothesis,Y)
        cost.backward()
        optimizer.step()

        avg_cost+=cost/total_batch

    print('epoch: {} cost: {}'.format(epoch+1,avg_cost))

print('learning finished')

epoch: 1 cost: 0.15979771316051483
epoch: 2 cost: 0.04317035526037216
epoch: 3 cost: 0.029908541589975357
epoch: 4 cost: 0.02232998237013817
epoch: 5 cost: 0.018295282498002052
epoch: 6 cost: 0.01512010209262371
epoch: 7 cost: 0.012980270199477673
epoch: 8 cost: 0.01045115664601326
epoch: 9 cost: 0.009223178029060364
epoch: 10 cost: 0.009032508358359337
epoch: 11 cost: 0.007143223658204079
epoch: 12 cost: 0.008653398603200912
epoch: 13 cost: 0.005579840857535601
epoch: 14 cost: 0.006424498278647661
epoch: 15 cost: 0.005773204378783703
learning finished


In [2]:
import torch
import torch.nn as nn
import torchvision.datasets as dsets
import torchvision.transforms as transforms
import torch.optim as optim

import torch.nn.init

device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')

torch.manual_seed(777)

if device=='cuda':
    torch.cuda.manual_seed_all(777)

# 파라미터 설정
learning_rate=0.015
training_epochs=15
batch_size=100

# 데이터셋 불러오기
mnist_train=dsets.MNIST(root='C:/git_experiment/RWL_Intern/dh_workspace/모두를 위한 딥러닝/MNIST',train=True,transform=transforms.ToTensor(),download=True)
mnist_test=dsets.MNIST(root='C:/git_experiment/RWL_Intern/dh_workspace/모두를 위한 딥러닝/MNIST',train=False,transform=transforms.ToTensor(),download=True)
data_loader=torch.utils.data.DataLoader(dataset=mnist_train, batch_size=batch_size, shuffle=True,drop_last=True)

# class 정의
class CNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.layer1=nn.Sequential(
            nn.Conv2d(1,32,3,stride=1,padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.layer2=nn.Sequential(
            nn.Conv2d(32,64,3,stride=1,padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.layer3=nn.Sequential(
            nn.Conv2d(64,128,3,stride=1,padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.fc1=nn.Linear(3*3*128,625)
        self.relu=nn.ReLU()
        self.fc2=nn.Linear(625,10,bias=True)
        torch.nn.init.kaiming_uniform_(self.fc1.weight)             # he 초기화는 kaiming_uniform 을 사용
        torch.nn.init.kaiming_uniform_(self.fc2.weight)

    def forward(self,x):
        out=self.layer1(x)
        out=self.layer2(out)
        out=self.layer3(out)

        out=out.view(out.size(0),-1)
        
        out=self.fc1(out)
        out=self.relu(out)
        out=self.fc2(out)

        return out

# model 정의
model=CNN().to(device)

# optimizer와 loss function 정의
optimizer=optim.Adam(model.parameters(),lr=learning_rate)
criterion=nn.CrossEntropyLoss().to(device)

total_batch=len(data_loader)
for epoch in range(training_epochs):
    avg_cost=0

    for X,Y in data_loader:
        X=X.to(device)
        Y=Y.to(device)

        optimizer.zero_grad()
        hypothesis=model(X)
        cost=criterion(hypothesis,Y)
        cost.backward()
        optimizer.step()

        avg_cost+=cost/total_batch

    print('epoch: {}, cost: {}'.format(epoch+1,avg_cost))

print('finished learning')

epoch: 1, cost: 0.2992653250694275
epoch: 2, cost: 0.11726064234972
epoch: 3, cost: 0.10683590918779373
epoch: 4, cost: 0.10272818058729172
epoch: 5, cost: 0.10507979989051819
epoch: 6, cost: 0.10775179415941238
epoch: 7, cost: 0.10779769718647003
epoch: 8, cost: 0.10426343232393265
epoch: 9, cost: 0.10197030752897263
epoch: 10, cost: 0.09687957167625427
epoch: 11, cost: 0.09840089082717896
epoch: 12, cost: 0.0968899354338646
epoch: 13, cost: 0.10430961102247238
epoch: 14, cost: 0.10163317620754242
epoch: 15, cost: 0.09393569082021713
finished learning


In [ ]:
exit()

: 