In [4]:
import numpy as np
import torch

ModuleNotFoundError: No module named 'torch'

In [8]:
# 1D array
t=np.arange(7)
print(t)

print(t[:4], t[2:4])

[0 1 2 3 4 5 6]
[0 1 2 3] [2 3]


In [11]:
# 2D array
t=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(t)
print(t.ndim)
print(t.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


In [1]:
import torch

In [2]:
t=torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])      #float형 텐서로 값을 만들겠다는 명령
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [5]:
# 1D array with pytorch
t=torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [7]:
print(t.dim())                      # rank
print(t.shape)                      # shape
print(t.size())                     # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [8]:
#2d array with pytorch

t=torch.FloatTensor([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

print(t)
print(t.dim())
print(t.shape)
print(t.size())
print(t[:,1])
print(t[:,1].size())
print(t[:, :-1])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [10]:
#Broad casting

#same shape
m1=torch.FloatTensor([[3,3]])
m2=torch.FloatTensor([[2,2]])
m1+m2

tensor([[5., 5.]])

In [11]:
# vector+scalar
m1=torch.FloatTensor([[1,2]])
m2=torch.FloatTensor([3])
m1+m2

tensor([[4., 5.]])

In [12]:
# 2x1 vector + 1x2 vector
m1=torch.FloatTensor([[1,2]])
m2=torch.FloatTensor([[3],[4]])
m1+m2

tensor([[4., 5.],
        [5., 6.]])

In [13]:
# 행렬곱은 matmul
m1=torch.FloatTensor([[1,2],[3,4]])         # 2x2
m2=torch.FloatTensor([[1],[2]])             # 2x1

m1.matmul(m2)

tensor([[ 5.],
        [11.]])

In [14]:
# 일반 곱셈
m1*m2                                       #브로드 캐스팅 됨.

tensor([[1., 2.],
        [6., 8.]])

In [16]:
# mean 함수
t=torch.FloatTensor([1,2])
t.mean()

tensor(1.5000)

In [17]:
# longtensor에서는 mena을 잘 못한다.
t=torch.LongTensor([1,2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [19]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [22]:
print(t.mean())                 # 전체에 대해
print(t.mean(dim=0))            # dim=0에 대해(dim=0 대신 그냥 0을 인수로 넣어도 dim=0처럼 나온다.)
print(t.mean(dim=1))            # dim=1에 대해
print(t.mean(dim=-1))           # 마지막 dim에 대해

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [23]:
# sum 함수. (mean과 비슷한 문법)

t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [25]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [26]:
# Max & Argmax


t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [27]:
print(t.max())          # max operator returns one value if it is called without an argument.

tensor(4.)


In [28]:
# max operator returns 2 values when called with dimension specified. the first value is the maximum value, 
# and the second value is the argmax: the index of the element with maximum value.
print(t.max(dim=0))         # max한 index값도 같이 출력한다.

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [29]:
print(t.max(dim=0)[0], t.max(dim=1)[1])

tensor([3., 4.]) tensor([1, 1])


In [30]:
print(t.max(dim=1)[0], t.max(dim=1)[1])

tensor([2., 4.]) tensor([1, 1])
