In [1]:
import numpy as np
import torch

In [3]:
# view(numpy에서의 Reshape)
t=np.array([[[0,1,2],
            [3,4,5]],

            [[6,7,8],
            [9,10,11]]
            ])

ft=torch.FloatTensor(t)
print(ft)
print(ft.shape)                 # 2x2x3=12

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])


In [5]:
print(ft.view([-1,3]))          # 리스트로 받는다. 그리고 인수에 -1이 들어오면 자동으로 dim을 맞추라는 소리다.
print(ft.view([-1,3]).shape)    # 4x3=12

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [7]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)  # 4x1x3=12

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [10]:
# squeeze (view와 비슷하지만, squeeze는 크기가 1인 차원을 제거하여 텐서의 크기를 변경한다.)

ft=torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [12]:
print(ft.squeeze())
print(ft.squeeze().shape)       #차원에서 크기 1이 사라지는 것을 알 수 있다.

tensor([0., 1., 2.])
torch.Size([3])


In [15]:
# dim을 이용해서 특정 차원의 크기 1을 제거 가능하다.
print(ft.squeeze(dim=1))

tensor([0., 1., 2.])


In [16]:
# 만약 크기가 1이 아닌 차원에 dim을 이용해서 squeeze를 하면 어케 될까?
print(ft.squeeze(dim=0))

tensor([[0.],
        [1.],
        [2.]])


In [18]:
# Unsqueeze
# : 원하는 dim에 1을 넣어준다. (dim 명시 필수다.)

ft=torch.FloatTensor([0, 1, 2])
print(ft)
ft.shape

tensor([0., 1., 2.])


torch.Size([3])

In [20]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [21]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [22]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [23]:
# Type Casting
# : tensor의 type을 바꿔준다.

lt=torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [28]:
print(lt.float())           # float으로 바꿔줌.
print(lt.float().dtype)

tensor([1., 2., 3., 4.])
torch.float32


In [29]:
bt=torch.ByteTensor([True, False, False, True])         # ByteTensor는 boolean값을 저장한다.
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [30]:
print(bt.long())                                        # 정수형으로 바꿔줌.
print(bt.float())                                       # 실수형형

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [35]:
# BoolTensor는 조건문을 실행할 때 유용하다. masking등에 활용할 수 있다.
bt=(lt==3)
print(bt)
print(bt.dtype)
print(bt.long())

tensor([False, False,  True, False])
torch.bool
tensor([0, 0, 1, 0])


In [38]:
# Concatenate (이어붙이다)          
# : cat함수를 사용한다.
x=torch.FloatTensor([[1,2],[3,4]])
y=torch.FloatTensor([[5,6],[7,8]])
print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [39]:
print(torch.cat([x,y],dim=0))
print(torch.cat([x,y],dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [45]:
z=torch.FloatTensor([[5,6,7],[9,10,11]])
print(torch.cat([x,z],dim=0))               # dim=0으로는 크기가 맞지 않아서 안됨.

RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 2 but got size 3 for tensor number 1 in the list.

In [47]:
z=torch.FloatTensor([[5,6,7],[9,10,11]])
print(torch.cat([x,z],dim=1))               # dim=1으로는 크기가 맞아서 된다.

tensor([[ 1.,  2.,  5.,  6.,  7.],
        [ 3.,  4.,  9., 10., 11.]])


In [56]:
# Stacking: Concatination을 편리하게 할 수 있다.
# 근데 torch.cat은 텐서들을 새로운 차원 생성 없이 붙이는 느낌이라면, torch.stack은 새로운 차원을 생성하여 텐서들을 붙인다.
x=torch.FloatTensor([1,4])
y=torch.FloatTensor([2,5])
z=torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))         #새로운 차원이 생성됨

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [57]:
print(torch.stack([x,y,z],dim=0))           # dim을 이용해서 붙일 수 있다.
print(torch.stack([x,y,z],dim=1))           

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [58]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)],dim=0))    #이렇게 하면 위의 stack dim=0과 같은 형태를 띈다.    
                                                                            #참고로 이렇게 하면 순서는 unsqueeze를 하고 나서 dim을 주고 cat을 한다.

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [59]:
#얘와 cat을 비교해봐라. 새로운 차원이 생긴다는 것도 알 수 있고 붙이는 방법도 다소 다르다.

x=torch.FloatTensor([[1,2],[3,4]])
y=torch.FloatTensor([[5,6],[7,8]])

print(torch.stack([x,y],dim=0))
print(torch.stack([x,y],dim=1))

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[[1., 2.],
         [5., 6.]],

        [[3., 4.],
         [7., 8.]]])


In [60]:
# Ones and Zeros
x=torch.FloatTensor([[0,1,2], [2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [64]:
#numpy의 ones_like와 zeroes_like와 같다.
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [78]:
#참고로 바로 one이나 zero로 이루어진 행렬을 만들 수 있다. 넘파이와 비슷하다.
print(torch.ones([4,4]))
print(torch.zeros((4,4)))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [83]:
# In-place Operation
# : 메모리에 새로 선언하지 않고 출력값을 기존의 Tensor에 넣는 방식
x=torch.FloatTensor([[1,2],[3,4]])

print(x.mul(2.))
print(x)                    # x에 저장되지 않음.
print(x.mul_(2))            # 언더바 _를 붙인 것에 주목.
print(x)                    # x에 저장됨.

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
