In [5]:
import numpy as np

A=np.array([[1,2],[4,5]])
print(A)
print(A.shape)
A.dtype

[[1 2]
 [4 5]]
(2, 2)


dtype('int32')

In [7]:
B=np.array([[3,6],[5,10]])

A*B

array([[ 3, 12],
       [20, 50]])

In [16]:
X=np.array([[51,55],[14,19],[0,4]])

X=X.flatten()
print(X)


#추출
print(X[[0,2,4]])               # 이건 리스트를 이용

#또는

print(X[np.array([0,2,4])])     # 이건 numpy를 이용


[51 55 14 19  0  4]
[51 14  0]
[51 14  0]


In [17]:
X>15                # 특정 조건을 만족하는 원소 얻을 수 있다. (대신 bool값으로 나옴)

array([ True,  True, False,  True, False, False])

In [20]:
X[X>15]             # 추출도 가능

array([51, 55, 19])